name = "tubonge-download-counter"
main = "src/index.mjs"
compatibility_date = "2026-03-06"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "tubonge-download-counter"
database_id = "51a1fe9e-c80b-4b1e-a98f-8b1e122b9221"
